"use strict";
const $=id=>document.getElementById(id),zone="America/Santiago";
const dates=new Intl.DateTimeFormat("es-CL",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"});
const scenarios={normal:"Operación normal",blocked_cooling:"Refrigeración reducida: calentamiento gradual",misalignment:"Desalineación inyectada: componente 2× elevada",cavitation:"Cavitación inyectada: ruido y rendimiento hidráulico reducido",signal_loss:"Pérdida de señal: el modelo sigue funcionando sin enviar",recovery:"Condiciones normales restauradas: recuperación gradual"};
const links={connected:["✓ Conectado","good"],connecting:["○ Conectando","neutral"],unavailable:["! Receptor no disponible","bad"],wrong_profile:["! Perfil incompatible","bad"],suspended:["■ Recepción suspendida","neutral"],disconnected:["■ Envío desconectado","neutral"],signal_loss:["○ Sin señal simulada","bad"],paused:["Ⅱ Simulador pausado","neutral"],rejected:["! Paquete rechazado","bad"],error:["! Error de envío","bad"]};
let state=null,settingsLoaded=false,lastSuccess=0;
const num=(n,d=1)=>Number(n).toLocaleString("es-CL",{minimumFractionDigits:d,maximumFractionDigits:d});
function notify(message,error=false){$("message").textContent=message;$("message").className="message"+(error?" error":"");$("message").hidden=false;}
async function api(path,data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4000);try{const response=await fetch(path,{signal:controller.signal,cache:"no-store",...(data===undefined?{}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)})});const payload=await response.json();if(!response.ok)throw Error(payload.error||"No se pudo completar.");return payload;}catch(e){throw Error(e.name==="AbortError"?"El simulador no respondió a tiempo.":e.message);}finally{clearTimeout(timer);}}
function badge(id,label,cls){$(id).textContent=label;$(id).className="badge "+cls;}
function clear(){for(const id of ["temperature","vibration"])$(id).textContent="—";$("plant").classList.remove("running","emitting");}
function render(s){state=s;lastSuccess=performance.now();$("offline").hidden=true;
 $("sensor-note").textContent=s.context.temperature_saturated?"! Límite del DS18B20 emulado: temperatura saturada en 125 °C; el modelo supera su rango.":"DS18B20 emulado · paso de 0,0625 °C";
 if(s.current){$("temperature").textContent=num(s.current.temperature_c,2);$("vibration").textContent=num(s.current.vibration_rms,2);}else clear();
 badge("model-state",s.error?"! Error del modelo":!s.running?"Ⅱ Simulación pausada":s.motor_on?"▶ Motor en marcha":"■ Motor detenido · enfriando",s.error?"bad":s.running&&s.motor_on?"good":"neutral");
 const [label,cls]=links[s.link.state]||links.error;badge("link-state",label,cls);$("link-message").textContent=s.link.message;$("last-received").textContent=s.link.last_received_at?"Última recepción confirmada: "+dates.format(new Date(s.link.last_received_at)):"Sin recepción confirmada";
 $("plant").classList.toggle("running",s.running&&s.context.rpm>50);$("plant").classList.toggle("emitting",s.running&&s.signal&&s.link.state==="connected");
 $("motor-start").disabled=s.motor_on;$("motor-stop").disabled=!s.motor_on;$("pause").disabled=!s.running;$("resume").disabled=s.running;$("connect").disabled=s.link.enabled;$("disconnect").disabled=!s.link.enabled;
 document.querySelectorAll("[data-scenario]").forEach(b=>{const selected=b.dataset.scenario===s.scenario;b.classList.toggle("selected",selected);b.setAttribute("aria-pressed",selected);});$("scenario-label").textContent=scenarios[s.scenario];
 const elapsed=Math.floor(s.elapsed_s),h=Math.floor(elapsed/3600),m=Math.floor(elapsed%3600/60),sec=elapsed%60;$("clock").textContent=`Tiempo del modelo: ${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`;
 $("time-badge").textContent=`Tiempo físico ${s.settings.time_scale}×`+(s.settings.time_scale>1?" · ACELERADO":"");
 if(!settingsLoaded){$("ambient").value=s.settings.ambient_c;$("valve").value=s.settings.valve_opening;$("time-scale").value=s.settings.time_scale;settingsLoaded=true;}
 for(const [id,key,d]of [["rpm","rpm",0],["flow","flow_m3h",1],["head","head_m",1]])$(id).textContent=s.context[key]===undefined?"—":num(s.context[key],d);$("load").textContent=s.context.load_fraction===undefined?"—":num(s.context.load_fraction*100,0);
 $("sequence").textContent="Secuencia de generación "+s.sequence;$("packet").textContent=s.packet?JSON.stringify(s.packet,null,2):!s.running?"Simulación pausada: no hay un paquete actual.":!s.signal?"Pérdida de señal: no hay paquete para enviar. El modelo continúa.":"Esperando un nuevo paquete.";
 $("transport-counts").textContent=`Confirmados en esta sesión: ${s.link.accepted} · Rechazados: ${s.link.rejected} · Intentos sin conexión: ${s.link.failures}. Sin cola de paquetes antiguos.`;
 const receiverURL=`http://127.0.0.1:${s.link.receiver_port}`;for(const id of ["receiver-link","receiver-nav"])$(id).href=receiverURL;
 if(s.error)notify(s.error,true);draw();}
function context(id){const c=$(id),rect=c.getBoundingClientRect();if(rect.width<1)return null;const ratio=window.devicePixelRatio||1;c.width=rect.width*ratio;c.height=rect.height*ratio;const ctx=c.getContext("2d");ctx.scale(ratio,ratio);ctx.clearRect(0,0,rect.width,rect.height);ctx.font="10px Segoe UI";return{ctx,w:rect.width,h:rect.height,l:45,r:12,t:12,b:28};}
function chart(id,field,color){const a=context(id);if(!a)return;const{ctx:x,w,h,l,r,t,b}=a,rows=state?.trend||[];if(!rows.length){x.fillStyle="#718792";x.fillText("Esperando generación de datos…",l,h/2);return;}const values=rows.map(v=>v[field]),min=Math.min(...values),max=Math.max(...values),pad=Math.max((max-min)*.15,field==="temperature_c"?1:.15),low=Math.max(0,min-pad),high=max+pad;const first=Date.parse(rows[0].at),range=Math.max(1000,Date.parse(rows.at(-1).at)-first);
 for(let i=0;i<4;i++){const y=t+i*(h-t-b)/3;x.strokeStyle="#edf2f4";x.beginPath();x.moveTo(l,y);x.lineTo(w-r,y);x.stroke();x.fillStyle="#748b96";x.textAlign="right";x.fillText((high-i*(high-low)/3).toFixed(1),l-8,y+3);}x.strokeStyle=color;x.lineWidth=2;x.beginPath();rows.forEach((v,i)=>{const px=l+(Date.parse(v.at)-first)/range*(w-l-r),py=t+(high-v[field])/(high-low)*(h-t-b);if(!i||Date.parse(v.at)-Date.parse(rows[i-1].at)>2500)x.moveTo(px,py);else x.lineTo(px,py);});x.stroke();
 const times=new Intl.DateTimeFormat("es-CL",{timeZone:zone,hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"});x.fillStyle="#748b96";x.textAlign="left";x.fillText(times.format(new Date(first)),l,h-7);x.textAlign="right";x.fillText(times.format(new Date(rows.at(-1).at)),w-r,h-7);$(id.replace("-chart","-range")).textContent=`Rango ficticio: ${num(min,2)}–${num(max,2)} · ${rows.length} paquetes. Eje temporal: reloj del PC; modelo ${state.settings.time_scale}×.`;}
function waveform(){const a=context("waveform");if(!a)return;const{ctx:x,w,h,l,r,t,b}=a,rows=state?.waveform||[];if(!rows.length)return;const high=Math.max(.2,...rows.flatMap(v=>[Math.abs(v.x),Math.abs(v.y),Math.abs(v.z)]))*1.1;
 for(let i=0;i<3;i++){const y=t+i*(h-t-b)/2;x.strokeStyle="#edf2f4";x.beginPath();x.moveTo(l,y);x.lineTo(w-r,y);x.stroke();x.textAlign="right";x.fillStyle="#748b96";x.fillText((high-i*high).toFixed(1),l-8,y+3);}for(const[key,color]of[["x","#338b7d"],["y","#537eaa"],["z","#9985b5"]]){x.strokeStyle=color;x.lineWidth=1.25;x.beginPath();rows.forEach((v,i)=>{const px=l+i/(rows.length-1)*(w-l-r),py=t+(high-v[key])/(2*high)*(h-t-b);if(i)x.lineTo(px,py);else x.moveTo(px,py);});x.stroke();}x.textAlign="left";x.fillText("0 ms",l,h-7);x.textAlign="right";x.fillText("119 ms",w-r,h-7);}
function draw(){chart("temperature-chart","temperature_c","#2b807b");chart("vibration-chart","vibration_rms","#547897");waveform();}
document.querySelectorAll("[data-action]").forEach(button=>button.addEventListener("click",async()=>{try{render(await api("/api/control",{action:button.dataset.action}));}catch(e){notify(e.message,true);}}));
$("settings-form").addEventListener("submit",async event=>{event.preventDefault();try{const settings=Object.fromEntries([...new FormData(event.target)].map(([k,v])=>[k,Number(v)]));render(await api("/api/settings",settings));notify("Entorno aplicado. La temperatura conserva su continuidad y evoluciona hacia las nuevas condiciones.");}catch(e){notify(e.message,true);}});
window.addEventListener("resize",draw);
async function poll(){try{render(await api("/api/status"));}catch(e){clear();$("offline").hidden=false;badge("model-state","! Servicio no disponible","bad");}finally{setTimeout(poll,1000);}}
setInterval(()=>{if(lastSuccess&&performance.now()-lastSuccess>5000){clear();$("offline").hidden=false;badge("model-state","○ Sin datos actuales","bad");}},250);poll();
