// Dos procesos reales y dos pantallas. Solo desarrollo; ninguna dependencia del producto.
const {chromium}=require(process.env.NEIRON_PLAYWRIGHT_MODULE||"playwright");
const {spawn}=require("node:child_process"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),net=require("node:net"),assert=require("node:assert/strict");
const root=path.resolve(__dirname,".."),artifacts=path.join(root,".test-artifacts","motor");fs.mkdirSync(artifacts,{recursive:true});
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"neiron-motor-browser-"));let receiver,simulator,browser,receiverURL,simURL;const report={started:new Date().toISOString(),checks:[],requests:[],temporaryData:temp};const errors=[];
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,message,timeout=15000){const start=Date.now();while(Date.now()-start<timeout){try{if(await fn())return;}catch{}await delay(250);}throw Error("Tiempo agotado: "+message);}
async function port(){const s=net.createServer();await new Promise(r=>s.listen(0,"127.0.0.1",r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
function spawnPython(args,name){const child=spawn(path.join(root,".venv","Scripts","python.exe"),args,{cwd:root,windowsHide:true,env:{...process.env,PYTHONUTF8:"1"},stdio:["ignore","pipe","pipe"]});for(const stream of [child.stdout,child.stderr])stream.on("data",d=>fs.appendFileSync(path.join(artifacts,"processes.log"),d));return child;}
async function close(child){if(child&&child.exitCode===null){const exit=new Promise(r=>child.once("exit",r));child.kill();await exit;}}
async function sim(){return(await fetch(simURL+"/api/status")).json();}async function status(){return(await fetch(receiverURL+"/api/status")).json();}
async function startReceiver(rp,sp){receiver=spawnPython(["-m","neiron.server","--port",String(rp),"--simulator-port",String(sp),"--profile","motor-pump","--input","external","--data-dir",path.join(temp,"receiver")],"receiver");await until(async()=>(await fetch(receiverURL+"/api/status")).ok,"inicio receptor");}
async function startSimulator(rp,sp){simulator=spawnPython(["-m","neiron.motor_server","--port",String(sp),"--receiver-port",String(rp),"--data-dir",path.join(temp,"simulator")],"simulator");await until(async()=>(await fetch(simURL+"/api/status")).ok,"inicio simulador");}
function check(text){report.checks.push(text);console.log("OK:",text);}
(async()=>{try{
 const rp=await port(),sp=await port();receiverURL=`http://127.0.0.1:${rp}`;simURL=`http://127.0.0.1:${sp}`;await startReceiver(rp,sp);await startSimulator(rp,sp);
 browser=await chromium.launch({executablePath:"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",headless:true});const context=await browser.newContext({viewport:{width:1440,height:1080},acceptDownloads:true});
 context.on("page",page=>page.on("pageerror",e=>errors.push(e.message)));await context.route("**/*",async route=>{const url=route.request().url();report.requests.push(url);if(url.startsWith(simURL+"/")||url.startsWith(receiverURL+"/"))await route.continue();else await route.abort();});
 const page=await context.newPage(),neiron=await context.newPage();await page.goto(simURL);await neiron.goto(receiverURL);await until(async()=>(await sim()).link.state==="connected"&&!!(await status()).current,"envío independiente");
 assert.equal((await status()).asset.id,"motor-bomba-5hp");assert.equal((await status()).current.device_id,"esp32-motor-simulado");assert.equal((await status()).current.vibration_method,"synthetic_vector_rms_1000hz");assert(await neiron.locator("#external-input").isVisible());assert(await neiron.locator("#internal-input").isHidden());assert.equal(await neiron.locator("#external-simulator-link").getAttribute("href"),simURL);
 await page.locator("#time-scale").selectOption("60");await page.click('#settings-form button[type="submit"]');await until(async()=>(await sim()).settings.time_scale===60,"escala temporal");await delay(4000);
 const current=await sim();assert.equal(current.context.sample_count,1000);assert.equal(current.context.sample_rate_hz,1000);assert(current.context.rpm>2900);assert(current.context.flow_m3h>17);check("Dos HTTP independientes, ESP32 emulado y neiron recibe temperatura/RMS con identidad de motor");
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(artifacts,"01-banco-motor.png"),fullPage:true});await neiron.screenshot({path:path.join(artifacts,"02-neiron-receptor.png"),fullPage:true});
 const full=(await sim()).context.flow_m3h;await page.locator("#valve").selectOption("0.5");await page.click('#settings-form button[type="submit"]');await delay(2200);assert((await sim()).context.flow_m3h<full);await page.locator("#valve").selectOption("1");await page.click('#settings-form button[type="submit"]');check("Válvula cambia caudal/carga y escala 60× acelera física manteniendo paquetes de reloj");
 await page.click('[data-action="misalignment"]');await until(async()=>(await status()).active_alarms.some(a=>a.kind==="vibration"),"alarma desalineación");await neiron.click('[data-view="alarms"]');await until(async()=>await neiron.locator("#alarm-list button").count()>0,"reconocimiento");await neiron.locator("#alarm-list button").first().click();await until(async()=>(await status()).active_alarms.some(a=>a.acknowledged_at),"causa permanece reconocida");
 await page.click('[data-action="recovery"]');await until(async()=>!(await status()).active_alarms.some(a=>a.kind==="vibration"),"recuperación vibración");
 await page.click('[data-action="cavitation"]');await until(async()=>(await status()).active_alarms.some(a=>a.kind==="vibration"),"cavitación inyectada");await page.click('[data-action="recovery"]');await until(async()=>!(await status()).active_alarms.some(a=>a.kind==="vibration"),"recuperación cavitación");check("Desalineación/cavitación inyectadas activan vibración; reconocimiento y recuperación quedan registrados");
 const before=(await sim()).current.temperature_c;await page.click('[data-action="blocked_cooling"]');const immediate=(await sim()).current.temperature_c;assert(Math.abs(immediate-before)<1);await until(async()=>(await status()).active_alarms.some(a=>a.kind==="temperature"),"calentamiento gradual y alarma térmica",80000);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(artifacts,"03-refrigeracion-reducida.png"),fullPage:true});await page.click('[data-action="recovery"]');await until(async()=>!(await status()).active_alarms.some(a=>a.kind==="temperature"),"enfriamiento y recuperación térmica",45000);check("Calentamiento continuo sin salto instantáneo y recuperación térmica con histéresis");
 await neiron.click('[data-view="monitor"]');await page.click('[data-action="signal_loss"]');await until(async()=>(await status()).state==="no_data","pérdida señal");await until(async()=>await neiron.locator("#temperature").textContent()==="—","no mostrar lectura vieja");assert.equal(await neiron.locator("#vibration").textContent(),"—");assert((await sim()).motor_on);assert((await sim()).running);await page.click('[data-action="recovery"]');await until(async()=>!!(await status()).current,"recuperar señal");check("Pérdida de señal deja física continua y neiron oculta ambos canales al vencer");
 await page.click("#motor-stop");await until(async()=>(await sim()).context.rpm<1,"apagar motor");assert((await sim()).running);assert((await status()).current);assert((await sim()).current.vibration_rms<.05);await page.click("#motor-start");await until(async()=>(await sim()).context.rpm>2900,"encender motor");
 await page.click("#pause");const elapsed=(await sim()).elapsed_s;await until(async()=>(await status()).state==="no_data","pausa sin paquetes");assert.equal((await sim()).elapsed_s,elapsed);await page.click("#resume");await until(async()=>!!(await status()).current,"reanudar");check("Apagar mantiene telemetría/enfriamiento; pausar detiene evolución/envío; reanudar conserva estado");
 await page.click("#disconnect");const startElapsed=(await sim()).elapsed_s;await until(async()=>(await status()).state==="no_data","desconexión envío");assert((await sim()).elapsed_s>startElapsed);await page.click("#connect");await until(async()=>(await sim()).link.state==="connected"&&!!(await status()).current,"reconectar");check("Desconectar envío no detiene el modelo; reconexión entrega datos nuevos");
 await neiron.click('[data-view="interventions"]');await neiron.locator('#intervention-form [name="author"]').fill("Prueba motor");await neiron.locator('#intervention-form [name="work_type"]').selectOption({label:"Inspección"});await neiron.locator('#intervention-form [name="observations"]').fill("Ensayo simulado del acoplamiento motor–bomba.");await neiron.click('#intervention-form button[type="submit"]');await until(async()=>await neiron.locator("#intervention-list .record").count()===1,"intervención motor");
 await neiron.click('[data-view="history"]');await neiron.locator("#history-to").fill(await neiron.evaluate(()=>localDate(Date.now()+3600000)));await neiron.click('#history-filter button[type="submit"]');await until(async()=>await neiron.locator("#history-rows tr").count()>10,"historial motor");const dl=neiron.waitForEvent("download");await neiron.click("#export");const download=await dl;await download.saveAs(path.join(artifacts,"motor.csv"));const csv=fs.readFileSync(path.join(artifacts,"motor.csv"),"utf8");assert(csv.includes("motor-bomba-5hp"));assert(csv.includes("synthetic_vector_rms_1000hz"));assert(csv.includes("simulated"));check("Historial, CSV e intervención usan el activo motor sin mezclar la lavadora");
 const seq=(await sim()).sequence,phys=(await sim()).elapsed_s;await close(receiver);await until(async()=>(await sim()).link.state==="unavailable","receptor cerrado");assert((await sim()).elapsed_s>phys);await startReceiver(rp,sp);await until(async()=>(await sim()).link.state==="connected"&&!!(await status()).current,"receptor reiniciado");assert((await status()).current.sequence>seq);assert.equal((await(await fetch(receiverURL+"/api/interventions")).json()).rows.length,1);check("Simulación continúa con receptor cerrado; reinicio conserva historial y recibe paquetes frescos");
 const saved=(await sim());await close(simulator);await startSimulator(rp,sp);await until(async()=>(await sim()).link.state==="connected","simulador reiniciado");assert((await sim()).sequence>saved.sequence);assert((await sim()).elapsed_s>=saved.elapsed_s);assert.equal((await sim()).settings.time_scale,60);assert((await sim()).current.temperature_c>25);check("Reinicio del simulador conserva secuencia, temperatura, tiempo físico y entorno");
 await page.reload();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,"04-movil.png"),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);assert(report.requests.every(u=>u.startsWith(simURL+"/")||u.startsWith(receiverURL+"/")));check("Pantalla de 390 px sin desbordamiento; sin errores JavaScript ni solicitudes externas");report.result="passed";
 }catch(e){report.result="failed";report.error=e.stack;console.error(e);process.exitCode=1;}
 finally{if(browser)await browser.close();await close(simulator);await close(receiver);report.finished=new Date().toISOString();fs.writeFileSync(path.join(artifacts,"report.json"),JSON.stringify(report,null,2));const resolved=path.resolve(temp);assert(resolved.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(resolved).startsWith("neiron-motor-browser-"));try{fs.rmSync(resolved,{recursive:true,force:true,maxRetries:3,retryDelay:200});}catch(e){report.cleanupWarning=resolved;fs.writeFileSync(path.join(artifacts,"report.json"),JSON.stringify(report,null,2));console.log("Base temporal conservada para limpieza:",resolved);}}
})();
